config/routes.rb
Rails.application.routes.draw do
  # root page is index of users
  get '/', to: 'users#index', as: 'landing'
  # can't edit tweet
  resources :tweets, except: :edit
  # user creation include in index view
  resources :users, except: :new
  # to see the followers of user
  get '/users/:id/followers', to: 'users#followers', as: 'followers'
  # to see people who follow user
  get '/users/:id/following', to: 'users#following', as: 'following'
  # to get user profile image
  get '/asset/users/:id/profile/', to: 'users#file', as: 'user_profile_img'



  # to connect user with his id
  get '/auth/:id/login', to: 'users#login', as: 'login'
  # to disconnect user with his id
  get '/auth/logout', to: 'users#logout', as: 'logout'


  # to get follow feed of authenticated user
  get '/following/', to: 'tweets#follow_feed', as: 'follow_feed'
  # to view tweets of an hashtag
  get '/hashtags/:hashtag', to: 'tweets#hashtag', as: 'hashtag'

  # to follow user
  get '/follow/:follow_user_id', to: 'follows#follow', as: 'follow'
  # to unfollow user
  get '/unfollow/:follow_user_id', to: 'follows#unfollow', as: 'unfollow'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags
  validates :tweet, presence: true, length: { maximum: 280 }

  # Automatically create hashtag based on # on tweet body
  after_create do
    tweet = Tweet.find_by(id: id)
    hashtags = self.tweet.scan(/#\w+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      tweet.tags << tag
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_session
  before_action :set_tweet, only: %i[ show edit update destroy]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /following/
  def follow_feed
    @tweets = []
    if !@user_auth.nil?
      Tweet.all.order('created_at DESC').each do |tweet|
        @tweets << tweet if @user_auth.followings.include?(tweet.user)
      end
    else
      raise ActionController::MethodNotAllowed, 'Veuillez vous connecter'
    end
  end

  # GET /hashtags/:hashtag
  def hashtag
    tag = Tag.order('created_at DESC').find_by(name: params[:hashtag])
    if !tag.nil?
      @tweets = tag.tweets
      @hashtag = tag.name
    else
      @tweets = []
      @hashtag = params[:hashtag]
    end
  end

  # GET /tweets/1
  def show
  end
  
  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'L\'OktoTweet a bien été créé' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  def destroy

    respond_to do |format|
      if @tweet.user.id == auth_user_id
        @tweet.destroy
        format.html { redirect_to tweets_url, notice: 'L\OktoTweet a bien été supprimer.' }
      else
        @tweets = Tweet.all
        format.html { redirect_to tweets_url, notice: 'Vous ne pouvez pas supprimer les tweets des autres utilisateurs' }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def set_session
    @user_auth = auth_user
  end
  # Only allow a list of trusted parameters through.
  def tweet_params
    @tweet_parms = params.require(:tweet).permit(:tweet)
    @tweet_parms[:user] = auth_user
    @tweet_parms
  end

  def auth_user
    User.find(auth_user_id) unless auth_user_id.nil?
  end

  def auth_user_id
    session[:current_user_id] unless session[:current_user_id].nil?
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  # replace every # by link to the hashtag
  def format_tweet_body(body)
    body = simple_format(body)
    body = body.gsub(/#\w+/)do |word|
      link_to word, controller: :tweets, action: 'hashtag', hashtag: word.downcase.delete('#')
    end.html_safe
    body.gsub(/@\w+/)do |word|
      if !User.find_by(login:word.delete('@')).nil?
        link_to word, controller: :users, action: 'show', id: User.find_by(login: word.delete('@')).id
      else
        word
      end
    end.html_safe

  end

  # get most popular hashtags
  def popular_hashtag
    Tag.find_by_sql('SELECT tags.*
                    FROM tags
                             inner join tags_tweets tt on tags.id = tt.tag_id
                    group by tags.id
                    ORDER BY count(*) desc
                    LIMIT 5;')

  end
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> a interdit l'envoie de ce tweet:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tweet %>
    <%= form.text_field :tweet %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_modal_form.erb
<div class="modal opacity-0 pointer-events-none fixed w-full h-full top-0 left-0 flex items-center justify-center">
  <div class="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"></div>

  <div class="modal-container bg-dark w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto rounded-3xl">
    <!-- Modal Upper Cross -->
    <div class="modal-close absolute top-0 right-0 cursor-pointer flex flex-col items-center mt-4 mr-4 text-white text-sm z-50">
      <svg class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
        <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
      </svg>
      <span class="text-sm">(Esc)</span>
    </div>
    <!-- Modal Shape -->
    <div <%=tweet.errors.any? ? 'id=asError' : '' %> class="modal-content py-4 text-left px-10 pt-6">
      <!--Title-->
      <div class="flex justify-between items-center pb-3">
        <h1 class="mb-0">OktoTweeter !</h1>
        <!-- Modal close button inside -->
        <div class="modal-close cursor-pointer z-50">
          <svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
            <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
          </svg>
        </div>
      </div>
      <%= form_with model: tweet, validate: true do |form| %>
        <div class="field">
          <%= form.text_area :tweet %>
        </div>
        <!--Footer-->
        <div class="flex justify-end pt-2">
          <button type="reset" class="modal-close px-4 bg-transparent p-3 rounded-lg text-red-imperial hover:bg-gray-100 hover:text-red-imperial mr-2">Annuler</button>
          <button type="submit" class="px-4 bg-red-imperial p-3 rounded-lg text-white hover:bg-blue-space">Envoyer</button>
        </div>
        </div>
      <% end %>
      </div>
</div>

app/views/tweets/new.html.erb
<div class="flew">
  <div class="topbar">
    <div class="backArrow" onclick="window.history.back()">
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-left" width="44" height="44" viewBox="0 0 24 24" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
        <line x1="5" y1="12" x2="19" y2="12" />
        <line x1="5" y1="12" x2="11" y2="18" />
        <line x1="5" y1="12" x2="11" y2="6" />
      </svg>
    </div>
    <h1>Ecrire un nouveau Oktotweet</h1>
  </div>
  <div class="defilable-thread">
    <%= render 'form', tweet: @tweet %>

    <%= link_to 'Back', tweets_path %>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="flew">
  <div class="topbar">
    <div class="backArrow" onclick="window.history.back()">
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-left" width="44" height="44" viewBox="0 0 24 24" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
        <line x1="5" y1="12" x2="19" y2="12" />
        <line x1="5" y1="12" x2="11" y2="18" />
        <line x1="5" y1="12" x2="11" y2="6" />
      </svg>
    </div>
    <h1>OktoTweeter</h1>
  </div>
  <div class="defilable-thread">
    <%= render 'component/tweet', tweet: @tweet %>
  </div>
</div>